# Site settings
title: Interpretting Non-Literal Language Use in the Built Environment
baseurl: "/ctrl"
url: "http://XII-SCRIPTA.github.io/ctrl"
#remote_theme: XII-SCRIPTA/ctrl 

# Build settings
markdown: kramdown

exclude:
- node_modules